name: "Run linting and tests"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:focal

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run lint-check
    - run: npm run compile
    - run: npm run -- docs --treatWarningsAsErrors

    - id: coverage
      uses: artiomtr/jest-coverage-report-action@v2
      with:
        test-script: npm run test
        output: report-markdown
    - uses: marocchino/sticky-pull-request-comment@v2
      with:
        message: ${{ steps.coverage.outputs.report }}
